name: PR Auto-Review Comment

on:
  pull_request:
    types: [opened]

jobs:
  add_auto_review_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add review comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEW_COMMENT_TEXT: '[КОММЕНТАРИЙ ДЛЯ РЕВЬЮ - СТАВЬ 👍]'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "${REVIEW_COMMENT_TEXT}"
